#!/usr/bin/env ruby

CONSUMER_KEY=""
CONSUMER_SECRET=""
ACCESS_TOKEN=""
ACCESS_TOKEN_SECRET=""

require_relative "lib/twitter"

command = ARGV.shift
lines =  twitter_app(command, ARGV)

lines.each do |line|
  puts line
end
